[project]
name = "fastapi-s3"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastapi[standard]>=0.115.13",
    "pydantic>=2.11.7",
    "taskipy>=1.14.1",
]

[tool.taskipy.tasks]
start = "uv run uvicorn main:app"
